id: P003040
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 10:36:29.076716
source_metadata:
  id: bdr:W3CN8194
  title: གསོ་རིག་འབུམ་བཞི་།
  author: ''
  volumes:
    9fdb9559c38645159cf92f248da5d2f8:
      image_group_id: I3CN8196
      title: ''
      volume_number: 1
      total_pages: 321
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
