id: I1FAAA3A7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T20:20:26+00:00'
last_modified: '2022-06-07T17:09:20.372595+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN8194
  title: གསོ་རིག་འབུམ་བཞི་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    51E8:
      image_group_id: I3CN8196
      title: ''
      total_pages: 321
      order: 1
      base_file: 51E8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
